### ISSUE TITLE
Support check authentication of an entry.

### ISSUE THREAD

**Issue by liudonghua123** [wstrange/dartdap#31]
After ldap Connection is connected and authenticated. If I want to query an entry and compare its plain password and the hashed salt password in `userPassword` attribute, then this feature is missing.

Can we implement this feature in the lib, rather then implement as a separated lib.

Some implementation of other languages are:

https://pypi.org/project/pySSHA/
https://www.npmjs.com/package/ldap-passwd

**Comment by hoylen** [comment]
Having it in a separate library is better, because there are many different types of hashes (and even plaintext) that can be stored in the `userPassword` attribute.

Therefore, it will be difficult for _dartdap_ to support them all. In fact, many of them are now considered insecure (e.g. MD5 and SHA1). So an implementation in _dartdap_ will have to choose between creating a security weakness for everyone, or for it to not work for some applications. It is better if the application implements its own checks, since it knows which hash algorithm it needs to support.

What type of hashes does your application want to support? It will be different to what someone else wants to support. For example, I use it with [crypt](https://pub.dev/packages/crypt) hashes.

In fact, your example "implementation of other languages" are separate libraries from the LDAP libraries!

**Comment by chrisridd** [comment]
What if you can’t read passwords? Or your server is using authPassword or another attribute?

From the protocol level the compare operation *might* work (but you need to know which attribute). The bind operation certainly will work, but it could change the account’s state (last login time, password failure counts, etc) which is highly undesirable. It could even lock the account.

I don’t think there’s a way to solve this.

**Comment by liudonghua123** [comment]
@hoylen @chrisridd Thanks for your explanations and suggestions. I am new to dart program language, I will try to implement a package to generate or check common userPassword like the examples in other language. Among the ldap implementation I experienced, all the user's password is stored as `userPassword` attribute with some hashed text prefixed with {SSHA}, {SSHA256} or similar.

**Comment by wstrange** [comment]
Thanks @liudonghua123.  I am going to close this issue for now.

**Comment by liudonghua123** [comment]
I write a simple package to provide this functionality.  
https://pub.dev/packages/ldap_passwd
